apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: deploy
  labels:
    app: deploy
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
      containers:
      - name: nginx
        image: 942368311701.dkr.ecr.us-east-1.amazonaws.com/techno-ecr-banjarbaru-iqbal:v1.1.0
        ports:
        - name: http
          containerPort: 2000