apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-deployment
  namespace: deploy
  labels:
    app: deploy
spec:
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
      containers:
      - name: nginx
        image: public.ecr.aws/nginx/nginx:1.23
        ports:
        - name: http
          containerPort: 2000