apiVersion: v1
kind: Service
metadata:
  name: app-service
  namespace: service
  labels:
    app: deploy
spec:
  selector:
    app: deploy
  ports:
    - protocol: TCP
      port: 2000
      targetPort: 2000